### ISSUE TITLE
libexpat.la not found

### ISSUE THREAD

**Issue by miktoki** [conda-forge/dbus-feedstock#1]
I tried installing `dbus` using a python2.7 environment in my python3.4 installation of conda(downloaded miniconda, then later installed the full ananconda through `conda`)but got the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '********/miniconda/envs/py27/lib/libexpat.la'`

`conda info` gives(replacing containing directory by '********'):

```
        platform : linux-64
        conda version : 4.1.6
        conda-env version : 2.5.1
        conda-build version : not installed
        python version : 3.4.4.final.0
        requests version : 2.9.1
        root environment : ********/miniconda  (writable)
        default environment : ********/miniconda/envs/py27
        envs directories : ********/miniconda/envs
        package cache : ********/miniconda/pkgs
        channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                    https://conda.anaconda.org/conda-forge/noarch/
                    https://repo.continuum.io/pkgs/free/linux-64/
                    https://repo.continuum.io/pkgs/free/noarch/
                    https://repo.continuum.io/pkgs/pro/linux-64/
                    https://repo.continuum.io/pkgs/pro/noarch/
        config file : *****/.condarc
        offline mode : False
        is foreign system : False
```

Is there some requirement or dependency that I am missing?

**Comment by mingwandroid** [comment]
@msarahan I think we should be deleting all .la files in post.py. They are a complete pain as they bake build-time paths in. Other distros take this approach.

**Comment by ocefpaf** [comment]
> @msarahan I think we should be deleting all .la files in post.py. They are a complete pain as they bake build-time paths in. Other distros take this approach.

:+1: to that I even opened an issue on `conda-forge` some time ago but was defeated. All Linux distros I know do delete them BTW.

**Comment by mingwandroid** [comment]
There's also the option to process them with some Python code and turn them into pkg-config .pc files instead. Cmake and autotools can grok those..

**Comment by ocefpaf** [comment]
Closing this as the proper solution is either to delete the `.la` files in `conda-build` or to ensure the `.la` has the prefix placeholder (the conda-forge version does have it BTW).

**Comment by mingwandroid** [comment]
I am in two minds about .la files. Keeping them can allow people to use your static librariesb with autotools, provided you fix-up the prefix.

**Comment by ocefpaf** [comment]
> provided you fix-up the prefix.

I noted in the past that conda-build did the right thing with `.la` files (not sure how that is in the the latest version though). Only a few old packages in `defaults` that were not build with `conda-build` suffer from that. So either way the problem reported here is not with the `libexpat.la` that comes from `conda-forge`.

PS: @miktoki you can check that by downloading https://anaconda.org/conda-forge/expat/2.1.0/download/linux-64/expat-2.1.0-2.tar.bz2 and opening the `.la` file. You will see the placeholders that should be replaced with the env prefix later.
